# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cargaHoraria', models.DecimalField(decimal_places=1, max_digits=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('dataCurso', models.DateField()),
                ('dataEmissao', models.DateField()),
                ('relatorio', models.TextField()),
                ('anexo', models.FileField(blank=True, default=None, upload_to=b'')),
                ('linkExterno', models.CharField(blank=True, max_length=200)),
                ('tipoAtividade', models.CharField(choices=[('1a', 'Eventos - Participa\xe7\xe3o'), ('1b', 'Eventos - Apresenta\xe7\xe3o de trabalho'), ('1c', 'Eventos - Interpreta\xe7\xe3o'), ('1d', 'Eventos - Organiza\xe7\xe3o'), ('2a', 'Defesas - Participa\xe7\xe3o'), ('2b', 'Defesas - Interpreta\xe7\xe3o'), ('3a', 'Pesquisa - Participa\xe7\xe3o como pesquisador'), ('3b', 'Pesquisa - Participa\xe7\xe3o como contribuidor de dados'), ('4a', 'Extens\xe3o - Participa\xe7\xe3o em projetos'), ('4b', 'Extens\xe3o - Participa\xe7\xe3o como aluno'), ('4b', 'Extens\xe3o - Participa\xe7\xe3o como especialista'), ('5a', 'Ensino - Monitoria em Letras-Libras'), ('5b', 'Ensino - Doc\xeancia em Libras'), ('6a', 'Publica\xe7\xe3o - Resumos'), ('6b', 'Publica\xe7\xe3o - Artigos completos'), ('6b', 'Publica\xe7\xe3o - Material did\xe1tico'), ('7a', 'Atividades culturais - Participa\xe7\xe3o'), ('7b', 'Atividades culturais - Atua\xe7\xe3o')], default=('1a', 'Eventos - Participa\xe7\xe3o'), max_length=200)),
                ('ISSN', models.IntegerField(blank=True)),
                ('ISBN', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='acc',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accs.Aluno'),
        ),
        migrations.AddField(
            model_name='acc',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
