# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('aluno', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('carga_horaria', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('data_do_curso', models.DateField()),
                ('data_de_emissao', models.DateField()),
                ('responsavel', models.CharField(max_length=200)),
                ('relatorio', models.TextField()),
                ('arquivo_anexado', models.FileField(blank=True, default=None, upload_to=b'')),
                ('link_externo', models.CharField(default=None, max_length=200)),
                ('tipo_atividade', models.CharField(choices=[('EaD', 'Ensino a Dist\xe2ncia'), ('PR', 'Presencial')], default='EaD', max_length=200)),
                ('codigo_de_publicacao_tipo', models.CharField(choices=[('ISSN', 'ISSN'), ('ISBN', 'ISBN')], default='ISSN', max_length=200)),
                ('codigo_de_publicacao', models.CharField(max_length=200)),
            ],
        ),
    ]
