# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('aluno', models.CharField(max_length=200)),
                ('matricula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('carga_horaria', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('data_do_curso', models.DateField()),
                ('data_de_emissao', models.DateField()),
                ('responsavel', models.CharField(max_length=200)),
                ('relatorio', models.TextField()),
            ],
        ),
    ]
