# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='acc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='acc',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acc',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accs.Aluno'),
        ),
        migrations.AlterField(
            model_name='acc',
            name='link_externo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
