# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='matricula',
            field=models.CharField(max_length=200),
        ),
    ]
