# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0002_auto_20170424_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='arquivo_anexado',
            field=models.FileField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='acc',
            name='tipo_atividade',
            field=models.CharField(choices=[('EaD', 'Ensino a Dist\xe2ncia'), ('PR', 'Presencial')], default='EaD', max_length=100),
        ),
    ]
