# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0003_auto_20170424_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='arquivo_anexado',
            field=models.FileField(blank=True, default=None, upload_to=b''),
        ),
    ]
