# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0004_auto_20170424_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='codigo_de_publicacao',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='acc',
            name='tipo_atividade',
            field=models.CharField(choices=[('EaD', 'Ensino a Dist\xe2ncia'), ('PR', 'Presencial')], default='EaD', max_length=200),
        ),
    ]
