# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0007_auto_20170424_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='codigo_de_publicacao_ISSN_ISBN',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
