# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0012_auto_20170424_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='codigo_de_publicacao',
            field=models.CharField(choices=[('ISSN', 'ISSN'), ('ISBN', 'ISBN')], max_length=200),
        ),
    ]
