# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0017_auto_20170424_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='codigo_de_publicacao',
        ),
    ]
