# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0018_remove_acc_codigo_de_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acc',
            old_name='codigo_de_publicacao_ISSN_ISBN',
            new_name='codigo_publicacao_ISSN_ISBN',
        ),
        migrations.AddField(
            model_name='acc',
            name='codigo_publicacao',
            field=models.CharField(blank=True, choices=[('ISSN', 'ISSN'), ('ISBN', 'ISBN')], default='ISSN', max_length=200, null=True),
        ),
    ]
