# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0019_auto_20170424_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='codigo_publicacao',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='codigo_publicacao_ISSN_ISBN',
        ),
        migrations.AddField(
            model_name='acc',
            name='codigo_publicacao_numero',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='acc',
            name='codigo_publicacao_tipo',
            field=models.CharField(choices=[('ISSN', 'ISSN'), ('ISBN', 'ISBN')], default='ISSN', max_length=200),
        ),
        migrations.AddField(
            model_name='acc',
            name='link_externo',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
