# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0020_auto_20170424_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='codigo_publicacao_numero',
        ),
        migrations.RemoveField(
            model_name='acc',
            name='codigo_publicacao_tipo',
        ),
    ]
